version: '3.8'

services:
  pamela:
    image: oldirtybenji/pamela-tee-agent:latest
    container_name: pamela-agent
    environment:
      - NODE_ENV=production
      - TEE_MODE=${TEE_MODE:-true}
      - PGLITE_DATA_DIR=/app/.eliza/.elizadb
      # Trading configuration
      - TRADING_ENABLED=${TRADING_ENABLED:-true}
      - UNSUPERVISED_MODE=${UNSUPERVISED_MODE:-true}
      - MAX_POSITION_SIZE=${MAX_POSITION_SIZE:-50}
      - MIN_CONFIDENCE_THRESHOLD=${MIN_CONFIDENCE_THRESHOLD:-0.7}
      # Core required variables
      - POLYMARKET_PRIVATE_KEY=${POLYMARKET_PRIVATE_KEY}
      - CLOB_API_URL=${CLOB_API_URL:-https://clob.polymarket.com}
      # News sources
      - NEWS_API_KEY=${NEWS_API_KEY:-}
      - TAVILY_API_KEY=${TAVILY_API_KEY:-}
      # Optional integrations
      - DISCORD_TOKEN=${DISCORD_TOKEN:-}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - TWITTER_API_KEY=${TWITTER_API_KEY:-}
    env_file:
      - .env
    volumes:
      - agent_data:/app/.eliza
    restart: unless-stopped
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 120s
    command: ["npm", "start"]

volumes:
  agent_data: