version: '3.8'

services:
  # PostgreSQL database for ElizaOS
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pamela
      POSTGRES_PASSWORD: pamela_dev
      POSTGRES_DB: pamela_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pamela"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Pamela Telegram Bot
  agent:
    build:
      context: .
      dockerfile: apps/agent/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Database
      DATABASE_URL: postgresql://pamela:pamela_dev@postgres:5432/pamela_db
      PGLITE_DATA_DIR: /app/data
      
      # Telegram Bot
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      
      # API Keys
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      POLYMARKET_PRIVATE_KEY: ${POLYMARKET_PRIVATE_KEY}
      CLOB_API_URL: ${CLOB_API_URL:-https://clob.polymarket.com/}
      
      # Trading Config
      TRADING_ENABLED: ${TRADING_ENABLED:-false}
      MAX_POSITION_SIZE: ${MAX_POSITION_SIZE:-100}
      MIN_CONFIDENCE_THRESHOLD: ${MIN_CONFIDENCE_THRESHOLD:-0.7}
      
      # Service Config
      NODE_ENV: development
      
      # Fixed Agent ID
      AGENT_ID: df35947c-da83-0a0a-aa27-c4cc3ec722cd
    ports:
      - "3001:3001"  # Health check port only
    volumes:
      - agent_data:/app/data
      - ./apps/agent:/app
      - /app/node_modules
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  agent_data: